sudo: false

addons:
  apt:
    packages:
    - rubberband-cli

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "3.6"

matrix:
    include:
        - python: 3.6
          dist: xenial
        - python: 3.7
          dist: xenial


before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    # install your own package into the environment
    - pip install -e .[tests]

script:
    - python --version
    - pytest

after_success:
    - coveralls
    - pip uninstall -y pyrubberband

after_failure:
    - pip uninstall -y pyrubberband
